create table course (
    id bigint generated by default as identity,
    title varchar(255) not null,
    creator_id bigint not null,
    cohort_id bigint not null,
    created_at timestamp not null,
    updated_at timestamp,
    primary key (id)
);

create table cohort (
    id bigint generated by default as identity,
    course_id bigint not null,
    name varchar(255) not null,
    primary key (id)
);

create table ns_user (
    id bigint generated by default as identity,
    user_id varchar(20) not null,
    password varchar(20) not null,
    name varchar(20) not null,
    email varchar(50),
    created_at timestamp not null,
    updated_at timestamp,
    primary key (id)
);

create table question (
    id bigint generated by default as identity,
    created_at timestamp not null,
    updated_at timestamp,
    contents clob,
    deleted boolean not null,
    title varchar(100) not null,
    writer_id bigint,
    primary key (id)
);

create table answer (
    id bigint generated by default as identity,
    created_at timestamp not null,
    updated_at timestamp,
    contents clob,
    deleted boolean not null,
    question_id bigint,
    writer_id bigint,
    primary key (id)
);

create table delete_history (
    id bigint not null,
    content_id bigint,
    content_type varchar(255),
    created_date timestamp,
    deleted_by_id bigint,
    primary key (id)
);

create table session (
    id bigint generated by default as identity,
    course_id bigint not null,
    cover_image_id bigint,
    title varchar(255) not null,
    status varchar(255) not null,
    price bigint not null,
    max_capacity int,
    enrolled_cnt int not null,
    start_date timestamp not null,
    end_date timestamp not null,
    primary key (id)
);

create table image (
    id bigint generated by default as identity,
    filename varchar(255) not null,
    size_in_bytes bigint not null,
    width_in_pixel int not null,
    height_in_pixel int not null,
    primary key (id)
);

create table enrollment(
    id bigint generated by default as identity,
    user_id varchar(255) not null,
    session_id bigint not null,
    primary key (id)
);
