create table course (
    id bigint generated by default as identity,
    title varchar(255) not null,
    creator_id bigint not null,
    created_at timestamp not null,
    updated_at timestamp,
    primary key (id)
);

create table ns_user (
    id bigint generated by default as identity,
    user_id varchar(20) not null,
    password varchar(20) not null,
    name varchar(20) not null,
    email varchar(50),
    created_at timestamp not null,
    updated_at timestamp,
    primary key (id)
);

create table question (
    id bigint generated by default as identity,
    created_at timestamp not null,
    updated_at timestamp,
    contents clob,
    deleted boolean not null,
    title varchar(100) not null,
    writer_id bigint,
    primary key (id)
);

create table answer (
    id bigint generated by default as identity,
    created_at timestamp not null,
    updated_at timestamp,
    contents clob,
    deleted boolean not null,
    question_id bigint,
    writer_id bigint,
    primary key (id)
);

create table delete_history (
    id bigint not null,
    content_id bigint,
    content_type varchar(255),
    created_date timestamp,
    deleted_by_id bigint,
    primary key (id)
);

create table student (
    id bigint generated by default as identity,
    name varchar(20) not null,
    email varchar(50),
    budget bigint,
    enroll_status varchar(20) not null default 'NONE',
    primary key (id)
);

create table session (
    id bigint generated by default as identity,
    start_date timestamp not null,
    end_date timestamp not null,
    phase varchar(20) not null default 'READY',
    recruit_status varchar(20) not null default 'OPEN',
    pricing_type varchar(20),
    participant_type varchar(20),
    capacity int,
    fee int,
    primary key (id)
);

create table payment (
    id bigint generated by default as identity,
    session_id bigint,
    ns_user_id bigint,
    amount bigint,
    created_at timestamp,
    primary key (id)
);

create table course_session (
    course_id bigint not null,
    session_id bigint not null,
    primary key (course_id, session_id)
);

create table session_student (
    session_id bigint not null,
    student_id bigint not null,
    primary key (session_id, student_id)
);

create table cover_image (
    session_id bigint not null,
    size int not null,
    type varchar(20) not null,
    width int not null,
    height int not null,
    primary key (session_id, size, type, width, height)
);
